title: Mattia Mazzoli
description: I'm a PhD student in Physics of Complex Systems at IFISC, Palma, Spain
# show_downloads: true
# google_analytics:
theme: jekyll-theme-minimal

icon: "https://github.com/mattiamazzoli/mattiamazzoli.github.io/blob/master/assets/ifisc.jpg"
